# This is a sample configuration file for kat.
# It specifies the commands to compile and execute programs in different languages,
# as well as the file extensions associated with each language.
# You can use this file as a starting point for your own configuration file,
# so feel free to modify or add to it as you see fit :).

[default]
# The default language to use if none is specified when running the cli.
language = "python 3"

[languages]
# To add a new language, create a new section with the format [languages.<language_name>].
# The language name should be the name of the language as it appears on kattis have a look at https://open.kattis.com/languages
# If the language name contains spaces, put it in quotes, as in the example below.

[languages."python 3"]
execute_command = "python {source_file}"
extensions = ["py"]
template = "template.py"

[languages.java]
compile_command = "javac -encoding UTF-8 -sourcepath {output_directory} -cp {output_directory}/* -d {output_directory} {source_file}"
execute_command = "java -cp {output_directory} {source_file_no_ext}"
extensions = ["java"]
template = "template.java"

[languages.c]
compile_command = "gcc -g -O2 -std=gnu11 -static -o {executable_path} {source_file} -lm"
execute_command = "{executable_path}"
extensions = ["c"]
template = "template.c"

[languages.cpp]
compile_command = "g++ -g -O2 -std=gnu++17 -static -o {executable_path} -lrt -Wl,--whole-archive -lpthread -Wl,--no-whole-archive {source_file}"
execute_command = "{executable_path}"
extensions = ["cpp"]
template = "template.cpp"

[languages.rust]
compile_command = "rustc -o {executable_path} -O --crate-type bin --edition=2018 {source_file}"
execute_command = "{executable_path}"
extensions = ["rs"]
template = "template.rs"
