name: Build and release kat to release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x86_64
            os_name: "Linux"
          - os: macos-latest
            target: x86_64-apple-darwin
            arch: x86_64
            os_name: "Darwin"
          - os: macos-latest
            target: aarch64-apple-darwin
            arch: arm64
            os_name: "Darwin"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --out-dir release

      - name: Rename binary with version
        run: mv release/kat release/kat-${{ github.event.release.tag_name }}-${{ matrix.os_name }}-${{ matrix.arch }}

      - name: Get sha256
        run: sha256sum release/kat > kat-${{ github.event.release.tag_name }}-${{ matrix.os_name }}-${{ matrix.arch }}.sha256

      - name: Upload artifacts
        uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: release/kat*
            tag: ${{ github.event.release.tag_name }}
            overwrite: true
            file_glob: true